In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('creditcard.csv')

In [3]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
df.shape

(284807, 31)

In [5]:
df.isnull().sum() #there is no null values

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [6]:
#This is a classification problem
df['Class'].value_counts() #huge diff btw 0 and 1(highly imbalanced)

0    284315
1       492
Name: Class, dtype: int64

In [7]:
x=df.drop('Class',axis=1)

In [8]:
x.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V20       V21       V22       V23       V24  \
0  0.098698  0.363787  ...  0.251412 -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425  ... -0.069083 -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  ...  0.524980  0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024  ... -0.208038 -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  ...  0.408542 -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  
0  0.128539 -0.189115  0.133558 -0.021053  149.62  
1  0.167170  0.125895 -0.008983  0.014724    2.69  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66  
3  0.647376 -0.221929  0.062723  0.061458  123.50  
4 -0.206010  0.502292  0.219422  0.215153   69.99  

[5 rows x 30 columns]

In [9]:
y=df['Class']

In [10]:
y.head()

0    0
1    0
2    0
3    0
4    0
Name: Class, dtype: int64

In [11]:
#imbalanced dataset doesn't affect ensemble techniques

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report#during imbalanced dataset dont just check accuracy
from sklearn.model_selection import KFold
import numpy as np
from sklearn.model_selection import GridSearchCV

In [13]:
log_class = LogisticRegression()
#hyper parameter tuning
grid ={'C':10.0**np.arange(-2,3),'penalty':['l2']}
cv = KFold(n_splits=5,shuffle=False)

In [14]:
10.0**np.arange(-2,3)  #10 to the power -2 to +2

array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02])

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.7,random_state=0)

In [16]:
clf = GridSearchCV(log_class,grid,cv=cv,n_jobs=-1,scoring='f1_macro') 
clf.fit(x_train,y_train)

F:\Anacondareinstall\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02]),
                         'penalty': ['l2']},
             scoring='f1_macro')

In [17]:
#f1_macro is a scoring parameter 0 is worst 1 is best(for classification problems)

In [18]:
y_pred = clf.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[198935     93]
 [    94    243]]
0.9990620219195947
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    199028
           1       0.72      0.72      0.72       337

    accuracy                           1.00    199365
   macro avg       0.86      0.86      0.86    199365
weighted avg       1.00      1.00      1.00    199365



In [19]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(x_train,y_train)

RandomForestClassifier()

In [20]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
#decision tree mostly helps in imbalanced datasets with good precision recall accuracy etc..

[[199009     19]
 [    82    255]]
0.9994933915180698
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    199028
           1       0.93      0.76      0.83       337

    accuracy                           1.00    199365
   macro avg       0.97      0.88      0.92    199365
weighted avg       1.00      1.00      1.00    199365



In [21]:
y_train.value_counts()

0    85287
1      155
Name: Class, dtype: int64

In [22]:
class_weight = dict({0:1,1:100}) 

In [23]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(class_weight=class_weight) #applying class weight
classifier.fit(x_train,y_train)

RandomForestClassifier(class_weight={0: 1, 1: 100})

In [24]:
y_pred = classifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[199011     17]
 [    94    243]]
0.9994432322624333
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    199028
           1       0.93      0.72      0.81       337

    accuracy                           1.00    199365
   macro avg       0.97      0.86      0.91    199365
weighted avg       1.00      1.00      1.00    199365



In [25]:
#Undersampling - reduces the points of the maximum labels
#mostly we dont use it because we lose data
#we can use if data is small

In [26]:
!pip install imbalanced-learn

In [27]:
y_train.value_counts()

0    85287
1      155
Name: Class, dtype: int64

In [28]:
from collections import Counter
Counter(y_train)

Counter({0: 85287, 1: 155})

In [29]:
!pip install imbalanced-learn

In [30]:
!pip install delayed

In [31]:
from imblearn.under_sampling import NearMiss

In [36]:
from imblearn.under_sampling import NearMiss
ns= NearMiss(0.25)
x_train_ns,y_train_ns = ns.fit_sample(x_train,y_train)
print("The no of classes before fit {}".format(counter(y_train)))
print("The no of classes after fit {}".format(counter(y_train_ns)))

AttributeError: 'NearMiss' object has no attribute 'fit_sample'

In [ ]:
#To be honesh randomforest is best on most cases

In [ ]:
#Over sampling - classes having less values , we will increase it

In [37]:
from imblearn.over_sampling import RandomOverSampler

#SMOTETomek
#SMOTETomek is somewhere upsampling and downsampling. SMOTETomek is a hybrid method which is a mixture of the above two methods, it uses an under-sampling method (Tomek) with an oversampling method (SMOTE). ... Class 0 has been downsampled from 500 to 472 and class 1 has been upsampled from 268 to 472.

In [38]:
from imblearn.combine import SMOTETomek #both undersampling and over sampling

In [39]:
# Ensemble Techniques

In [40]:
from imblearn.ensemble import EasyEnsembleClassifier

In [41]:
easy = EasyEnsembleClassifier()
easy.fit(x_train,y_train)

AttributeError: 'EasyEnsembleClassifier' object has no attribute 'n_features_in_'